<?php
require_once 'vendor/autoload.php';

$git = new CzProject\GitPhp\Git;
$path = '/Users/landonborges/Side Projects/blogging-with-bear/public'; // absolute path to public folder generated by bear-export.php
$repo_url = 'https://github.com/CoolandNiceGuy/bear-blog-posts.git'; // url for repository that will store your files

function publish_changes() {
  global $git, $path, $repo_url;

  $publish_repo = $git->init($path);
  $publish_repo->addAllChanges();
  $date = date('Y-m-d H:i:s', time()); // timestamp for commit message
  $publish_repo->commit($date);
  $publish_repo->addRemote('origin', $repo_url);
  $publish_repo->push(['origin', 'main'], ['-u', '-f']);
}
?>